/* ============================================
   DEFINITELY NOT A TROLL GAME™ — Level Data
   10 levels of escalating trust issues
   ============================================ */

const LEVELS = [

  // ===== LEVEL 1: WELCOME TO SAFETY =====
  // Tutorial: teaches basic movement. Everything honest. Builds false trust.
  {
    name: "WELCOME TO SAFETY",
    subtitle: "A perfectly normal tutorial level",
    bg: ['#0a0e1a','#0d1a3a','#12254a'],
    groundColor: '#1a2744', groundTop: '#2a3d66', accentColor: '#00e5ff',
    map: [
      "                                                               ",
      "                                                               ",
      "                                                               ",
      "                                                               ",
      "                                                               ",
      "                                                               ",
      "                                       o                       ",
      "                                      ---                      ",
      "            o o                o o           o o               ",
      "           -----    o      ---------       -------    o        ",
      "   o o o     T   ----   ##        o o       ---       ---  E   ",
      " P       ##  ###      ##   ##  ##     ^^  ##     ##  ####  ## ",
      "######  ########  ########  ########  ######  ########  ##### ",
      "######  ########  ########  ########  ######  ########  ##### ",
      "######  ########  ########  ########  ######  ########  ##### ",
    ],
    playerStart: [1, 11],
    signs: [
      { tx: 4, ty: 10, text: "Collect coins! They help! →", color: '#00e5ff' },
      { tx: 18, ty: 10, text: "Jump with W or SPACE", color: '#00e676' },
      { tx: 42, ty: 8, text: "→ EXIT ahead! Almost there!", color: '#ffd600' },
    ],
    trapCoinStart: 99, coinTrapChance: 0,
    spikeHeals: false, healthPackDamage: false,
    completeMsg: "That was... suspiciously normal. Enjoy it while it lasts. 🤔",
  },

  // ===== LEVEL 2: TRUST ISSUES =====
  // The betrayal begins. Spikes heal, health packs damage. Signs LIE.
  {
    name: "TRUST ISSUES",
    subtitle: "Everything is exactly what it seems",
    bg: ['#12081f','#1a0d2a','#2a1240'],
    groundColor: '#1f1035', groundTop: '#3a2255', accentColor: '#ff2d6a',
    map: [
      "                                                                              ",
      "                                                                              ",
      "                                                                              ",
      "                                                                              ",
      "                                                                              ",
      "                                                                              ",
      "                                                  o o o                        ",
      "                                                 -------                       ",
      "                                    o o                         o              ",
      "            ^^         ----       ------   +              ----  ---    D       ",
      "   o + o   ----   ^^   ###   + o        ---      o o  ^^         ---     E    ",
      " P       ##    ##     ##   ##   ^^    ##      ##       ##   ##  ####  ####    ",
      "######  #####  ####  ######  ######  #####  ######  #####  #### ##### ####    ",
      "######  #####  ####  ######  ######  #####  ######  #####  #### ##### ####    ",
      "######  #####  ####  ######  ######  #####  ######  #####  #### ##### ####    ",
    ],
    playerStart: [1, 11],
    signs: [
      { tx: 7, ty: 9, text: "⚠ AVOID SPIKES AT ALL COSTS!", color: '#ff4466' },
      { tx: 25, ty: 9, text: "Health pack ahead! Grab it! ♥", color: '#00e676' },
      { tx: 47, ty: 9, text: "← EXIT is behind you!", color: '#ffd600' },
      { tx: 62, ty: 9, text: "DANGER! DO NOT ENTER →", color: '#ff4466' },
    ],
    trapCoinStart: 0, coinTrapChance: 0,
    spikeHeals: true, healthPackDamage: true,
    completeMsg: "Plot twist: the spikes were the good guys all along. 🤯",
  },

  // ===== LEVEL 3: COIN ROULETTE =====
  // Every coin is a gamble. 50% chance it takes your score.
  {
    name: "COIN ROULETTE",
    subtitle: "Every coin is a gamble",
    bg: ['#0f1a0a','#152e0f','#1d4215'],
    groundColor: '#1a3314', groundTop: '#2d5522', accentColor: '#ffd600',
    map: [
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                o                         o                             ",
      "         o   o ---  o o           o   o  ---   o o                      ",
      "        --------- ------    o   --------     ------   o   o o          ",
      "   o o o      ---     #### o o o      ---       ####   o ---   E       ",
      " P       ^^  ##     ##       ---   ^^  ##   ##       ##     ##  ###    ",
      "###### ######  ####  ######  ######  ######  ####  ######  ####  ####  ",
      "###### ######  ####  ######  ######  ######  ####  ######  ####  ####  ",
      "###### ######  ####  ######  ######  ######  ####  ######  ####  ####  ",
    ],
    playerStart: [1, 11],
    signs: [
      { tx: 5, ty: 10, text: "Collect ALL the coins! 💰", color: '#ffd600' },
      { tx: 22, ty: 10, text: "The more coins the better!", color: '#ffd600' },
      { tx: 44, ty: 9, text: "Jackpot ahead! →→→", color: '#00e676' },
    ],
    trapCoinStart: 999, coinTrapChance: 0.5,
    spikeHeals: false, healthPackDamage: false,
    completeMsg: "50% of those coins robbed you. How's your trust fund? 📉",
  },

  // ===== LEVEL 4: THE FLOOR IS SUS =====
  // SAFE platforms everywhere in critical paths. They collapse.
  {
    name: "THE FLOOR IS SUS",
    subtitle: "All platforms thoroughly safety-tested™",
    bg: ['#1a0a0a','#2a1212','#3a1a1a'],
    groundColor: '#331a1a', groundTop: '#552d2d', accentColor: '#ff9100',
    map: [
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                                              o o                       ",
      "              o o              o             SSSSSS     o               ",
      "           SSSSSS      o o  SSSSSS   ----      o o   SSSS    o         ",
      "   o o o       o o  SSSS       o o         ---         o o       E     ",
      " P       ##  ##     ##      ##  ^^    ##       ^^   ##     ## ####     ",
      "######  ########  ######  ########  ######  ######  ######  ######     ",
      "######  ########  ######  ########  ######  ######  ######  ######     ",
      "######  ########  ######  ########  ######  ######  ######  ######     ",
    ],
    playerStart: [1, 11],
    signs: [
      { tx: 10, ty: 8, text: "✅ SAFE™ Certified Platform ↓", color: '#00e676' },
      { tx: 22, ty: 9, text: "✅ ISO-9001 Approved ↓", color: '#00e676' },
      { tx: 36, ty: 8, text: "✅ 100% load-tested ↓", color: '#00e676' },
      { tx: 52, ty: 8, text: "✅ Trust this one ↓", color: '#00e676' },
    ],
    trapCoinStart: 999, coinTrapChance: 0.3,
    spikeHeals: false, healthPackDamage: false,
    completeMsg: "'ISO-9001 Approved' by who exactly? Not us. 🤔",
  },

  // ===== LEVEL 5: OPPOSITE DAY =====
  // EVERYTHING is inverted + signs actively mislead about directions.
  {
    name: "OPPOSITE DAY",
    subtitle: "Nothing means what it says",
    bg: ['#0a1a1a','#0d2a2a','#104040'],
    groundColor: '#0f2f2f', groundTop: '#1a4545', accentColor: '#00ffaa',
    map: [
      "                                                                             ",
      "                                                                             ",
      "                                                                             ",
      "                                                                             ",
      "                                                                             ",
      "                                                                             ",
      "                                                                             ",
      "                                          o o o                              ",
      "                             o     o    -------           o                  ",
      "       ^^   + +    ----   ------  ---          ^^   +   ---      D           ",
      "   o + o   ----  ^^    ##        + o  ----  ---   o o      o o      E       ",
      " P       ##   ##     ##    ## ^^   ##     ##    ^^   ##  ##  ######  ##     ",
      "###### ######  ####  ####  ######  #####  ######  ######  ######  ######    ",
      "###### ######  ####  ####  ######  #####  ######  ######  ######  ######    ",
      "###### ######  ####  ####  ######  #####  ######  ######  ######  ######    ",
    ],
    playerStart: [1, 11],
    signs: [
      { tx: 6, ty: 9, text: "☠ DEADLY SPIKES! AVOID!", color: '#ff4466' },
      { tx: 16, ty: 9, text: "♥ Health = guaranteed SAFE", color: '#00e676' },
      { tx: 36, ty: 8, text: "← ← ← EXIT IS LEFT ← ← ←", color: '#ffd600' },
      { tx: 60, ty: 9, text: "⚠ DEAD END! GO BACK! ⚠", color: '#ff4466' },
    ],
    trapCoinStart: 0, coinTrapChance: 0.4,
    spikeHeals: true, healthPackDamage: true,
    completeMsg: "On Opposite Day, losing is winning. So you lost. Congrats? 🎉",
  },

  // ===== LEVEL 6: NARROW ESCAPE =====
  // Precision platforming with small platforms and tight jumps.
  {
    name: "NARROW ESCAPE",
    subtitle: "One wrong step and it's over",
    bg: ['#0a0a1f','#0f0f33','#141455'],
    groundColor: '#141433', groundTop: '#1f1f55', accentColor: '#7c4dff',
    map: [
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                                                                        ",
      "                                                     o                  ",
      "                                                    --                  ",
      "                    o          o         o                o              ",
      "         o   --   ---    o   ---   o   ---    --    ---  ---   o        ",
      "   o   ---         o o  ##      ---    o    ##       o o         E      ",
      " P   ##    ^^  ##       ^^  ##       ##   ^^      ##  ^^  ## ####      ",
      "####  ####  ######  ####  ######  ####  ####  ####  ####  ######       ",
      "####  ####  ######  ####  ######  ####  ####  ####  ####  ######       ",
      "####  ####  ######  ####  ######  ####  ####  ####  ####  ######       ",
    ],
    playerStart: [1, 11],
    signs: [
      { tx: 8, ty: 10, text: "Precision required.", color: '#7c4dff' },
      { tx: 40, ty: 9, text: "Almost there... probably.", color: '#7c4dff' },
    ],
    trapCoinStart: 999, coinTrapChance: 0.35,
    spikeHeals: false, healthPackDamage: false,
    completeMsg: "Your palms are sweaty. Mom's spaghetti. 🍝",
  },

  // ===== LEVEL 7: DÉJÀ VU =====
  // Looks IDENTICAL to Level 1 but everything is inverted and coins betray you.
  {
    name: "DÉJÀ VU",
    subtitle: "Haven't we been here before?",
    bg: ['#0a0e1a','#0d1a3a','#12254a'],
    groundColor: '#1a2744', groundTop: '#2a3d66', accentColor: '#00e5ff',
    map: [
      "                                                               ",
      "                                                               ",
      "                                                               ",
      "                                                               ",
      "                                                               ",
      "                                                               ",
      "                                       o                       ",
      "                                      ---                      ",
      "            o o                o o           o o               ",
      "           -----    o +    ---------       -------    o        ",
      "   o + o         ----   ##      + o o       ---       ---  E   ",
      " P       ##  ###      ##   ##  ##     ^^  ##     ##  ####  ## ",
      "######  ########  ########  ########  ######  ########  ##### ",
      "######  ########  ########  ########  ######  ########  ##### ",
      "######  ########  ########  ########  ######  ########  ##### ",
    ],
    playerStart: [1, 11],
    signs: [
      { tx: 4, ty: 10, text: "Relax. It's Level 1 again.", color: '#00e5ff' },
      { tx: 18, ty: 10, text: "Same rules, same coins ✅", color: '#ffd600' },
      { tx: 42, ty: 8, text: "Nothing has changed. Trust us.", color: '#00e676' },
    ],
    trapCoinStart: 0, coinTrapChance: 0.65,
    spikeHeals: true, healthPackDamage: true,
    completeMsg: "It LOOKED like Level 1... but nothing was real. Never was. 😈",
  },

  // ===== LEVEL 8: NO EXIT =====
  // 3 fake doors that kill you. Real exit is hidden.
  {
    name: "NO EXIT",
    subtitle: "The exit is... somewhere. Probably.",
    bg: ['#1a0a14','#2a1020','#3a1630'],
    groundColor: '#33142a', groundTop: '#552244', accentColor: '#ff2d6a',
    map: [
      "                                                                              ",
      "                                                                              ",
      "                                                                              ",
      "                                                                              ",
      "                                                                              ",
      "                                                                              ",
      "                                                                              ",
      "                                                                              ",
      "              o o          o o                       o                         ",
      "           ------      ------      D      ---     -----    D          E       ",
      "   o o o     ---   ^^    ####    D     o      ^^        o o      ######       ",
      " P       ## ##  ##     ##    ##     ## ## ##     ##   ##   ##  ##             ",
      "######  #####  ####  ######  ######  ######  ######  #####  #####  ######     ",
      "######  #####  ####  ######  ######  ######  ######  #####  #####  ######     ",
      "######  #####  ####  ######  ######  ######  ######  #####  #####  ######     ",
    ],
    playerStart: [1, 11],
    signs: [
      { tx: 8, ty: 9, text: "→ EXIT THIS WAY →→→", color: '#ffd600' },
      { tx: 25, ty: 9, text: "← Actually go left ←", color: '#ffd600' },
      { tx: 42, ty: 9, text: "→ REAL EXIT (trust me) →", color: '#00e676' },
      { tx: 58, ty: 9, text: "← No wait, go back ←", color: '#ff9100' },
    ],
    trapCoinStart: 999, coinTrapChance: 0.45,
    spikeHeals: false, healthPackDamage: false,
    completeMsg: "3 wrong doors. 3 deaths. 1 real exit. Worth it? 🚪",
  },

  // ===== LEVEL 9: THE GAUNTLET =====
  // Maximum difficulty. Everything inverted. Spikes heal, health hurts. 60% trap coins.
  {
    name: "THE GAUNTLET",
    subtitle: "Good luck. You'll need it.",
    bg: ['#0a0000','#1a0505','#2a0a0a'],
    groundColor: '#1a0000', groundTop: '#330000', accentColor: '#ff0000',
    map: [
      "                                                                                    ",
      "                                                                                    ",
      "                                                                                    ",
      "                                                                                    ",
      "                                                                                    ",
      "                                                                                    ",
      "                                                                                    ",
      "                                                                       o            ",
      "                    o              o           o           o           ---           ",
      "       ^^  + --  ^^  ---  ^^  + --   ---  ^^  --  + ^^  ---     D          E       ",
      "  o o  --     ^^  ##    --   ##   ^^    ##   --   ^^   ##     ######   ## ####      ",
      " P   ##  ^^  ##   ^^  ##  ^^   ##  ^^   ##   ^^  ##  ^^  ##        ##             ",
      "####  ####  ######  ####  ######  ####  ####  ######  ####  ######  ####  ######   ",
      "####  ####  ######  ####  ######  ####  ####  ######  ####  ######  ####  ######   ",
      "####  ####  ######  ####  ######  ####  ####  ######  ####  ######  ####  ######   ",
    ],
    playerStart: [1, 11],
    signs: [
      { tx: 6, ty: 10, text: "👋 Goodbye.", color: '#ff0000' },
      { tx: 60, ty: 9, text: "→ one more door...", color: '#ff4466' },
    ],
    trapCoinStart: 0, coinTrapChance: 0.6,
    spikeHeals: false, healthPackDamage: true,
    completeMsg: "You survived The Gauntlet. The game is impressed. (It's lying.) 💀",
  },

  // ===== LEVEL 10: THE BUTTON =====
  // The finale. Just press the button. It runs away.
  {
    name: "THE BUTTON",
    subtitle: "Just. Press. The. Button.",
    bg: ['#0a0008','#1a0010','#2a0020'],
    groundColor: '#1a0016', groundTop: '#3a1a35', accentColor: '#ffd600',
    isButtonLevel: true,
    map: [
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      " P                    B                  ",
      "########################################",
      "########################################",
      "########################################",
      "########################################",
    ],
    playerStart: [1, 10],
    signs: [],
    trapCoinStart: 999, coinTrapChance: 0,
    spikeHeals: false, healthPackDamage: false,
    completeMsg: "You did it. The universe thanks you. Or does it? 🌌",
  },
];
